SET(CTEST_PROJECT_NAME "AusweisApp2")
SET(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "cdash")
SET(CTEST_DROP_LOCATION "/submit.php?project=AusweisApp2")
SET(CTEST_DROP_SITE_CDASH TRUE)
