set(CTEST_PROJECT_NAME "AusweisApp2")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash")
set(CTEST_DROP_LOCATION "/submit.php?project=AusweisApp2")
set(CTEST_DROP_SITE_CDASH TRUE)
