exclude = [
    ".git",
    ".git-rewrite",
    ".hg",
    ".ruff_cache",
    "patch.py",
]

line-length = 79
indent-width = 4

[lint]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
