block()
	include(Files)
endblock()

set(API_JSON ${WORKSPACE}/api.json)
download_file(${API_JSON} $ENV{ANDROID_API_KEY})
find_package(Python REQUIRED)
file(GLOB apkfiles "${WORKSPACE}/*.apk")
file(GLOB debugSymbols "${WORKSPACE}/*.native-debug-symbols.zip")
step(${Python_EXECUTABLE} ${CMAKE_SOURCE_DIR}/ci/playstore.py --json ${API_JSON} --upload ${apkfiles} --symbols ${debugSymbols})
