if(RELEASE)
	if(DEFINED ENV{GITLAB_CI})
		set(FILE_TAG $ENV{REV})
	else()
		set(FILE_TAG $ENV{changeset})
	endif()
elseif(REVIEW)
	if(DEFINED ENV{GITLAB_CI})
		set(FILE_TAG $ENV{CI_JOB_NAME_SLUG}-$ENV{CI_PIPELINE_ID})
	else()
		set(FILE_TAG $ENV{BUILD_TAG})
	endif()
else()
	if(DEFINED ENV{GITLAB_CI})
		set(FILE_TAG $ENV{REVISION})
	else()
		set(FILE_TAG $ENV{MERCURIAL_REVISION_SHORT})
	endif()
endif()

step(${T_CFG} --preset ci-tools)

step(${T_TARGET} notes)
step(${T_TARGET} notes.latex.pdf)
step(${CMAKE_COMMAND} -E tar cfJ ../AusweisApp-${FILE_TAG}-ReleaseNotes.tar.xz . CHDIR ${T_BUILD_DIR}/docs/notes)

step(${T_TARGET} sdk)
step(${T_TARGET} sdk.latex.pdf)
step(${CMAKE_COMMAND} -E tar cfJ ../AusweisApp-${FILE_TAG}-SDK.tar.xz . CHDIR ${T_BUILD_DIR}/docs/sdk/html)

step(${T_TARGET} failurecodes)
step(${T_TARGET} failurecodes_en.latex.pdf)
step(${T_TARGET} failurecodes_de.latex.pdf)

step(${T_TARGET} installation_integration_de.latex.pdf)
step(${T_TARGET} installation_integration_en.latex.pdf)

step(${T_TARGET} license)

if(NOT RELEASE)
	step(${T_TARGET} doc8)
endif()
