apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ausweisapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
        - args:
            - /data/redis.conf
          image: redis:alpine
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              name: 6379tcp02
              protocol: TCP
          resources:
            limits:
              cpu: '10'
              memory: 40Gi
            requests:
              cpu: 500m
              memory: 8Gi
          securityContext:
            capabilities: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
