apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-ausweisapp-sync
  name: sync
  namespace: ausweisapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-ausweisapp-sync
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-ausweisapp-sync
      namespace: ausweisapp
    spec:
      containers:
        - env:
            - name: FINGERPRINTS
              valueFrom:
                secretKeyRef:
                  key: FINGERPRINT
                  name: generic-secrets
                  optional: false
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SWARM_PASSWORD
                  name: generic-secrets
                  optional: false
          image: dev-docker.governikus.de/ausweisapp2/alpine:sync
          imagePullPolicy: Always
          name: sync
          resources:
            requests:
              cpu: '5'
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /ssh
              name: ssh
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: ssh
          secret:
            defaultMode: 420
            optional: false
            secretName: generic-secrets
