CMAKE_MINIMUM_REQUIRED(VERSION 3.7.1)

SET(ANDROID_SDK $ENV{ANDROID_HOME})
SET(ANDROID_BUILD_TOOLS_REVISION $ENV{ANDROID_BUILD_TOOLS_REVISION})

SET(CMAKE_SYSTEM_NAME Android)
SET(CMAKE_ANDROID_STL_TYPE gnustl_shared)

IF(NOT CMAKE_ANDROID_ARCH_ABI)
	SET(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
ENDIF()

IF(CMAKE_ANDROID_ARCH_ABI MATCHES "arm64-v8a")
	SET(CMAKE_SYSTEM_VERSION 21)
ELSE()
	SET(CMAKE_SYSTEM_VERSION 18)
ENDIF()
