set(PROJECT_VERSION_MAJOR 2)
set(PROJECT_VERSION_MINOR 5)
set(PROJECT_VERSION_PATCH 1)
#set(PROJECT_VERSION_TWEAK 0)

unset(PROJECT_VERSION)
list(APPEND PROJECT_VERSION ${PROJECT_VERSION_MAJOR})
list(APPEND PROJECT_VERSION ${PROJECT_VERSION_MINOR})
list(APPEND PROJECT_VERSION ${PROJECT_VERSION_PATCH})
list(APPEND PROJECT_VERSION ${PROJECT_VERSION_TWEAK})
string(JOIN "." PROJECT_VERSION ${PROJECT_VERSION})

set(PROJECT_NAME AusweisApp)
