name: CI_build

"on": [push, pull_request]

env:
  BUILD_DIR_APP: "../_build"

jobs:

  build_windows:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Ninja"]

    steps:

      - name: Install openssl dev, ninja, wix
        run: |
          choco install openssl --version=4.0.3
          choco install ninja
          dotnet tool install --global wix

      - name: Add nmake
        uses: TheMrMilchmann/setup-msvc-dev@368ef7d1ee4d1171b31d4a7f67f4d954f903f5a9  # v4.1.0
        with:
          arch: x64

      - name: checkout files with lineending LF to overcome issue with yamllint on windows
        run: |
          git config --global core.autocrlf false

      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.01

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730  # v4.3.1
        with:
          version: '6.10.*'
          modules: 'qtscxml qtwebsockets qtshadertools qtconnectivity qtimageformats'
          setup-python: 'false'

      - name: vcpkg build
        uses: johnwason/vcpkg-action@04c68c847bf5196ecaa72331ecf51208583916ef  # v8.0.0
        id: vcpkg
        with:
          pkgs: llhttp
          triplet: x64-windows-release
          token: ${{ github.token }}

      - name: generate cmake
        run: |
          cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -G "${{ matrix.build_platform }}" `
                -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B "${{ env.BUILD_DIR_APP }}"

      - name: build cmake
        run: |
          cmake --build "${{ env.BUILD_DIR_APP }}" --config ${{ matrix.build_configuration }} --target package
          cmake --install "${{ env.BUILD_DIR_APP }}"

      - name: run ctest
        run: |
          ctest --test-dir ${{ env.BUILD_DIR_APP }} --output-on-failure -C "${{ matrix.build_configuration }}" --output-junit junit.xml

      - name: Report Test results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2  # v3.0.0
        if: success() || failure()
        with:
          name: ctest Tests
          path: ${{ env.BUILD_DIR_APP }}/junit.xml
          reporter: java-junit


  build_linux:

    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Ninja"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.01

      - name: Install packages via apt
        run: |
          sudo apt update -qq && sudo apt install -y cmake pkg-config libssl-dev libudev-dev libllhttp-dev libpcsclite-dev \
                                                     libgl1-mesa-dev qt6-l10n-tools ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730  # v4.3.1
        with:
          version: '6.11.*'
          modules: 'qtscxml qtwebsockets qtshadertools qtconnectivity'
          setup-python: 'false'

      - name: generate cmake
        run: |
          cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B ${{ env.BUILD_DIR_APP }}

      - name: build cmake
        run: |
          cmake --build ${{ env.BUILD_DIR_APP }} --config ${{ matrix.build_configuration }} --target package
          sudo cmake --install ${{ env.BUILD_DIR_APP }}

      - name: run ctest
        run: |
          ctest --test-dir ${{ env.BUILD_DIR_APP }} --output-on-failure -C "${{ matrix.build_configuration }}" --output-junit junit.xml

      - name: Report Test results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2  # v3.0.0
        if: success() || failure()
        with:
          name: ctest Tests
          path: ${{ env.BUILD_DIR_APP }}/junit.xml
          reporter: java-junit


  build_macos:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release]
        build_platform: ["Ninja"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.01

      - name: install llhttp
        run: |
             brew install llhttp

      - name: install ninja
        run: |
          brew install ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730  # v4.3.1
        with:
          version: '6.11.*'
          modules: 'qtscxml qtwebsockets qtshadertools qtconnectivity qtimageformats'

      - name: generate cmake
        run: |
          export OPENSSL_ROOT=/usr/local/opt/openssl/bin
          export LDFLAGS=-L/usr/local/opt/openssl/lib
          export CPPFLAGS=-I/usr/local/opt/openssl/include
          export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig/
          cmake -G "${{ matrix.build_platform }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_configuration }}" -B ${{ env.BUILD_DIR_APP }}

      - name: build cmake
        run: |
          cmake --build ${{ env.BUILD_DIR_APP }} --config ${{ matrix.build_configuration }}

      - name: run ctest
        run: |
          ctest --test-dir ${{ env.BUILD_DIR_APP }} --output-on-failure -C "${{ matrix.build_configuration }}" --output-junit junit.xml

      - name: Report Test results
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2  # v3.0.0
        if: success() || failure()
        with:
          name: ctest Tests
          path: ${{ env.BUILD_DIR_APP }}/junit.xml
          reporter: java-junit
