include_guard(GLOBAL)

set(ENV{REVIEW_PATCH} "${CMAKE_BINARY_DIR}/patch.diff")

function(IMPORT_PATCH _out)
	message(STATUS "Import from patch: $ENV{REVIEW_PATCH}")
	find_package(Python REQUIRED)
	step(${Python_EXECUTABLE} ${CI_DIR}/import.py --patch $ENV{REVIEW_PATCH} ${ARGN} NO_ECHO OUTPUT output CHDIR ${CMAKE_SOURCE_DIR})
	if(output MATCHES "Pending patch: (.+)")
		string(STRIP "${CMAKE_MATCH_1}" PENDING_PATCH)
		set(${_out} "${PENDING_PATCH}" PARENT_SCOPE)
	endif()
endfunction()


function(RESPAWN_PATCHED)
	if(SPLIT)
		set(SPLIT_PARAM --split)
	endif()
	if(NOT PATCHED)
		set(CLEAN_PARAM --clean)
	endif()
	if(REPATCH)
		set(REPATCH_PARAM --repatch)
	endif()

	if(NOT PATCHED OR SPLIT)
		unset(PENDING_PATCH CACHE)
		IMPORT_PATCH(PENDING_PATCH ${SPLIT_PARAM} ${CLEAN_PARAM} ${REPATCH_PARAM})

		if(PENDING_PATCH OR NOT PATCHED)
			set(PATCHED_OPTION "-DPATCHED=ON")
			if(NOT PATCHED_OPTION IN_LIST DEFINITIONS)
				list(APPEND DEFINITIONS ${PATCHED_OPTION})
			endif()

			set(PENDING_PATCH_OPTION "-DPENDING_PATCH")
			list(FILTER DEFINITIONS EXCLUDE REGEX "${PENDING_PATCH_OPTION}")
			if(PENDING_PATCH)
				list(APPEND DEFINITIONS "${PENDING_PATCH_OPTION}=${PENDING_PATCH}")
			endif()

			set(CHECKSUM_OPTION "-DCHECKSUM")
			list(FILTER DEFINITIONS EXCLUDE REGEX "${CHECKSUM_OPTION}")
			list(APPEND DEFINITIONS "${CHECKSUM_OPTION}=${CHECKSUM}")

			if(NOT PATCHED AND SPLIT)
				set(INITIAL_RUNNER INITIAL_RUNNER_FAILED)
			endif()

			message(STATUS "script runner: respawn")
			step(${CMAKE_COMMAND} ${DEFINITIONS} -P ${CMAKE_SCRIPT_MODE_FILE} -- ${PARAMS} NO_ECHO RESULT ${INITIAL_RUNNER})
			if(INITIAL_RUNNER)
				if(CLEAN)
					IMPORT_PATCH(_unused --clean-only)
				endif()
				if(INITIAL_RUNNER_FAILED)
					message(FATAL_ERROR "script runner: failed")
				else()
					message(STATUS "script runner: done")
				endif()
			endif()
		endif()
	endif()
endfunction()


function(PROCESS_REVIEW)
	if(NOT PATCHED AND DEFINED ENV{GITLAB_CI})
		if(DEFINED ENV{PATCH_URL})
			step(uv pip install python-hglib)
			handle_http("$ENV{REVIEW_PATCH}" URLS $ENV{PATCH_URL})
		elseif(DEFINED ENV{REVIEWBOARD_REVIEW_REQUEST})
			step(uv pip install rbtools python-hglib)
			step(rbt patch --write $ENV{REVIEW_PATCH} --server $ENV{REVIEWBOARD_SERVER} --diff-revision $ENV{REVIEWBOARD_DIFF_REVISION} $ENV{REVIEWBOARD_REVIEW_REQUEST})
		elseif(EXISTS "$ENV{REVIEW_PATCH}")
			message(STATUS "Use existing patch: $ENV{REVIEW_PATCH}")
		else()
			message(FATAL_ERROR "Unknown patch source")
		endif()
	endif()
	RESPAWN_PATCHED()
endfunction()


function(LIST_PATCH_FILES _out)
	if(PENDING_PATCH)
		set(regex "^(---|\\+\\+\\+) [ab]/")
		file(STRINGS "${PENDING_PATCH}" filelines REGEX "${regex}")
		foreach(line ${filelines})
			string(REGEX REPLACE "${regex}" "" line "${line}")
			list(APPEND out ${line})
		endforeach()
		list(REMOVE_DUPLICATES out)
		list(SORT out)
		set(${_out} ${out} PARENT_SCOPE)
	endif()
endfunction()
